
theme = "congo"
baseURL = "https://hakrSchool.com/"
defaultContentLanguage = "en"
languageCode = "en"
enableRobotsTXT = true
paginate = 10
summaryLength = 0

[outputs]
  home = ["HTML", "RSS", "JSON"]
